apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k6-operator
  namespace: argocd
spec:
  source:
    # path: argo-docker-test
    path: charts/k6-operator
    repoURL: "https://github.com/Blackboxops1/kubernetes-service-catalog"
    targetRevision: main
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
